### ISSUE TITLE
vpn connected, No internet

### ISSUE THREAD

**Issue by ecol0408** [iMrDJAi/cordova-plugin-tun2socks-udp-associate#3] opened 2021-08-05 09:50 UTC
vpn connected, but unable to access the network

**Comment by iMrDJAi** [comment] 2021-08-05 14:56
@ecol0408 "VPN connected" means that `tun2socks` is running. The issue is likely related to the socks v5 proxy server itself, or the connection between `tun2socks` and your server.  
Can you show me your setup, your code and also the logs from `logcat`? I can't really help you without any context.

**Comment by ecol0408** [comment] 2021-08-06 01:05
The code is the latest on the cloned github, integrated into the native app, and then I modified the runTun2Socks interface, adding the username and password parameters, and the others have not changed

**Comment by iMrDJAi** [comment] 2021-08-06 17:43
@ecol0408 Well, I told you it depends on the server you're trying to connect to itself. Since you said you were able to integrate the plugin into a native app successfully, you should take a look on the logs to see if there are issues with DNS resolving (the socks v5 proxy server should support UDP associate), and again you should make sure that the server is hosted on your device itself, you won't be able to connect to any external server directly. Would you mind if you post the logs here?

**Comment by ecol0408** [comment] 2021-08-07 13:17
Understood, is this a socks5 server that can only be used on a LAN?

I don’t know the c language part very well, there are too many logs after connecting, I don’t know which part to intercept

**Comment by iMrDJAi** [comment] 2021-08-07 14:47
@ecol0408 Yes, but in fact `LAN` is inaccurate, the correct term here is simply `localhost` since `tun2socks` can only connect to a server at the device scope itself. Therefore, you have to run a local proxy server on your app to handle the traffic form `tun2socks`, then you can forward it to a remote server from there. You should be able to find some `java` libraries that do the job for you, personally I used my own socks v5 `js` library ([socks5.js](https://github.com/iMrDJAi/socks5.js)) running on [nodejs-mobile-cordova](https://github.com/JaneaSystems/nodejs-mobile-cordova).  

If you're using Android studio, you should be able to filter the logs output, just use `tun2socks` as the search keyword.

**Comment by ecol0408** [comment] 2021-08-07 15:48
OK, thanks. I'll try

**Closed as completed** 2021-08-09 07:05 UTC
Labels: help wanted
